### ISSUE TITLE
Koa2

### ISSUE THREAD

**Issue by janbaer** [technicallyjosh/koa-better-validation#2]
Have you ever tried it with Koa2? Have you any plans to make it compatible with Koa2? Thanks

**Comment by dotjoshrc** [comment]
Hey @janbaer sorry for the late reply! Actually yes, I'm in the process of a re-factor/re-write for koa 2 currently. Just started this week! Since this was a fork with updates, it will most likely be a re-write from the ground up.

**Comment by dotjoshrc** [comment]
@janbaer I've put up a repo of my new validation lib for Koa. It's not published yet but will be within the next few days! I feel like it is a much cleaner implementation written from the ground up.

You can check it out [here](https://github.com/technicallyjosh/koa-fluent-validation).
